package test;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import beans.Bus;
import beans.Car;
import beans.Truck;

public class Client {
	public static void main(String[] args) {
		ApplicationContext ac = new ClassPathXmlApplicationContext("resources/spring.xml");

		System.out.println("----Car----");
		Car ob = (Car) ac.getBean("c");
		System.out.println(ob.myCarEngine().getEngineName());

		/*
		 * used to check class name of an object
		 * 
		 * Runtime proxy code is generated by spring (child class of Car)
		 */
		System.out.println(ob.getClass().getCanonicalName());
		System.out.println("----Bus----");
		Bus b = (Bus) ac.getBean("b");
		System.out.println(b.myBusEngine().getEngineName());
		System.out.println(b.getClass().getCanonicalName());

		System.out.println("----Truck----");
		Truck t = (Truck) ac.getBean("t");
		System.out.println(t.myTruckEngine().getEngineName());
		System.out.println(t.getClass().getCanonicalName());
	}
}
